name: SetsGenerator
version: '${project.version}'
main: org.betterbox.setsGenerator.SetsGenerator
api-version: '1.18'
load: POSTWORLD
authors: [ Grzybol ]
softdepend:
  - ElasticBuffer
commands:
  sg:
    description: Main command for SetsGenerator.
    usage: /sg <reloadconfig|spawnnpc>
    permission: setsGenerator.admin
    permission-message: You do not have permission to use this command.
